/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AllMoneyBlock: typeof import('./src/components/AllMoneysBlock/AllMoneyBlock.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    ButtonItem: typeof import('./src/components/Buttons/ButtonItem.vue')['default']
    ButtonLogReg: typeof import('./src/components/ButtonLogReg/ButtonLogReg.vue')['default']
    ButtonsList: typeof import('./src/components/Buttons/ButtonsList.vue')['default']
    Calendar: typeof import('./src/components/ui/calendar/Calendar.vue')['default']
    CalendarCell: typeof import('./src/components/ui/calendar/CalendarCell.vue')['default']
    CalendarCellTrigger: typeof import('./src/components/ui/calendar/CalendarCellTrigger.vue')['default']
    CalendarGrid: typeof import('./src/components/ui/calendar/CalendarGrid.vue')['default']
    CalendarGridBody: typeof import('./src/components/ui/calendar/CalendarGridBody.vue')['default']
    CalendarGridHead: typeof import('./src/components/ui/calendar/CalendarGridHead.vue')['default']
    CalendarGridRow: typeof import('./src/components/ui/calendar/CalendarGridRow.vue')['default']
    CalendarHeadCell: typeof import('./src/components/ui/calendar/CalendarHeadCell.vue')['default']
    CalendarHeader: typeof import('./src/components/ui/calendar/CalendarHeader.vue')['default']
    CalendarHeading: typeof import('./src/components/ui/calendar/CalendarHeading.vue')['default']
    CalendarNextButton: typeof import('./src/components/ui/calendar/CalendarNextButton.vue')['default']
    CalendarPrevButton: typeof import('./src/components/ui/calendar/CalendarPrevButton.vue')['default']
    DepositMoneyFrom: typeof import('./src/components/AllMoneysBlock/DepositMoneyFrom.vue')['default']
    EarningsList: typeof import('./src/components/ListMoney/EarningssList/EarningsList.vue')['default']
    EarningsListItem: typeof import('./src/components/EarningsList/EarningsListItem.vue')['default']
    ExpensesBlock: typeof import('./src/components/ExpensesBlock/ExpensesBlock.vue')['default']
    ExpensesList: typeof import('./src/components/ListMoney/ExpensesList/ExpensesList.vue')['default']
    ExpensesListItem: typeof import('./src/components/ExpensesList/ExpensesListItem.vue')['default']
    HeaderOfEarningList: typeof import('./src/components/ListMoney/HeaderOfEarningList.vue')['default']
    HeaderOfExpenssesList: typeof import('./src/components/ListMoney/HeaderOfExpenssesList.vue')['default']
    IForm: typeof import('./src/components/IForm.vue')['default']
    IModal: typeof import('./src/components/IForm/IModal.vue')['default']
    InputComp: typeof import('./src/components/Input/InputComp.vue')['default']
    ListMoney: typeof import('./src/components/ListMoney/ListMoney.vue')['default']
    LogForm: typeof import('./src/components/LogForm/LogForm.vue')['default']
    MoneyCircle: typeof import('./src/components/AllMoneysBlock/MoneyCircle.vue')['default']
    MoneyGoForm: typeof import('./src/components/AllMoneysBlock/MoneyGoForm.vue')['default']
    Popover: typeof import('./src/components/ui/popover/Popover.vue')['default']
    PopoverContent: typeof import('./src/components/ui/popover/PopoverContent.vue')['default']
    PopoverTrigger: typeof import('./src/components/ui/popover/PopoverTrigger.vue')['default']
    RegForm: typeof import('./src/components/RegForm/RegForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatItem: typeof import('./src/components/ExpensesBlock/StatItem.vue')['default']
  }
}
